upstream backend_api {
  least_conn;            # 启用最少连接算法，选择当前连接数最小的后端，避免请求堆积在慢的服务器上
  server server:3000;    # 这里 server 是服务名，Docker DNS 会返回多个 IP
}

server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  charset utf-8; # 防止中文乱码

  add_header X-Frame-Options "SAMEORIGIN"; # 禁止别的网站把你的页面放进 <iframe> 里套娃，防点击劫持
  add_header X-XSS-Protection "1; mode=block"; # 开启浏览器内置 XSS 攻击防护
  add_header X-Content-Type-Options "nosniff"; # 禁止浏览器自动 “猜” 文件类型

  # 开启 Nginx 的 gzip_static 压缩
  gzip_static on; 
  gzip_vary on;

  # Vue 路由模式支持
  location / {
    try_files $uri $uri/ /index.html; # 解决 History 模式刷新 404 问题
    expires -1; # 首页不缓存，强制浏览器每次都向服务器请求最新版
    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
  }
  
  # 后端 API 代理（所有 /api 请求转发给 app 服务）
  location /api {
    # proxy_pass http://server:3000;
    proxy_pass http://backend_api;      # 改用 upstream 轮发到多个 IP
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # 隐藏 Nginx 版本号（安全）
  server_tokens off;
}